spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_engine
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true

app.kafka.order-lifecycle.enabled=true
app.kafka.order-lifecycle.topic=order.lifecycle.v1
app.outbox.publisher.fixed-delay-ms=5000
app.outbox.publisher.batch-size=50

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

server.port=8080
